### ISSUE TITLE
Anti tatsumaki security

### ISSUE THREAD

**Issue by Mattlau04** [olegispe/autofish#1]
Sometimes, when tatsumaki notices your timing is too perfect, it puts a longer delay (20 sec or something like that)
It would be great to catch these, and to wait the said ammont of time

**Comment by olegispe** [comment]
Could do that, I'll have a look; I'm not entirely sure how to do that except from requesting 5 seconds after (to avoid command cooldown) and waiting the specified time, which could come up as a red flag for them.

**Comment by Mattlau04** [comment]
maybe get the specified time and add a random intinger ?
